### ISSUE TITLE
Initializaction failed

### ISSUE THREAD

**Issue by cosmico89** [macxq/foxess-ha#83]
I have a problem, it has been working great for 5 days, but today it gives me errors, I don't think anything has been changed.
this is the first error in the log
`FoxESS Cloud initializaction failed, fix error and restar ha`
and the other error:
`Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.`
it happened to someone else, I can't find a solution
Thanks!

**Comment by alexmercerscott** [comment]
I have the same problem. The integration work on 2022.10.5, but fails on 2022.11

Did you happen up update your HA recently?

The spelling of "initialisation" is exactly as the error message in the log appears.

`This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:167 
Integration: foxess (documentation, issues) 
First occurred: 22:39:29 (1 occurrences) 
Last logged: 22:39:29

FoxESS Cloud initializaction failed, fix error and restar ha`

**Comment by alexmercerscott** [comment]
The other error associated with this is as follows:

`This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: components/rest/data.py:63 
Integration: foxess (documentation, issues) 
First occurred: 22:39:29 (1 occurrences) 
Last logged: 22:39:29

Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
    raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.

`

**Comment by benbeton** [comment]
after reverting back to 2022.10.5 it ist working fine again

**Comment by titchy** [comment]
I can confirm the issue is related to versions of HA after 2022.10.x

**Comment by fossy50** [comment]
I have the same problem. The integration work on  Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest

2022-11-04 09:00:54.272 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration foxess which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-04 09:01:18.416 DEBUG (MainThread) [custom_components.foxess.sensor] Updating data from https://www.foxesscloud.com/
2022-11-04 09:01:18.417 DEBUG (MainThread) [custom_components.foxess.sensor] Token is empty, authenticating for the firts time
2022-11-04 09:01:18.482 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
2022-11-04 09:01:18.509 DEBUG (MainThread) [custom_components.foxess.sensor] Finished fetching FoxESS data in 0.092 seconds (success: False)
2022-11-04 09:01:18.509 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha

**Comment by sebastian-bugajny** [comment]
Same problem happened to me yesterday. I had to rollback HA to version 2022.10.5

**Comment by fossy50** [comment]
> Same problem happened to me yesterday. I had to rollback HA to version 2022.10.5
Hi, I want to avoid this, do you know if the problem can be solved soon?

**Comment by Grimroper** [comment]
Ive have the same problem.  Since upgrading to Home Assistant Core 2022.11.0 the Foxess-ha integration is failing to connect.  Its reporting an error "Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance."

```
This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: components/rest/data.py:63
Integration: foxess (documentation, issues)
First occurred: 12:01:32 (1 occurrences)
Last logged: 12:01:32

Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
    raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.
```

Issue persists after restarts and having upgraded to Core 2022.11.01.  Issue wasnt present in 2022.10.5 which I have restored back to and can confirm its working as expected.

Full log details are

```
2022-11-04 12:01:32.028 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
token = await authAndgetToken(hass, username, hashedPassword)
File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
await restAuth.async_update()
File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
response = await self._async_client.request(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
response = await self._send_handling_auth(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
response = await self._send_single_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.
2022-11-04 12:01:32.039 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha
```

**Comment by kevinverelst** [comment]
I can relate and have the same issue. I'm trying to downgrade now and see if it is resolved

**Comment by Weiss68** [comment]
I had the same issue all day yesterday after updating, downgraded today and all is fine again.

**Comment by kevinverelst** [comment]
I have a HA installation running on docker where I can easily downgrade the version so it works but when I try to run it on my dedicated odroid n2+, it seems that updating is part of the installation process and I'm stuck with the latest HA which breaks this HACS integration. Any ideas?

**Comment by amamoh** [comment]
Just ordered parts to build local integration for Foxess 
https://github.com/assembly12/Foxess-T-series-ESPHome-Home-Assistant

**Comment by spitfire** [comment]
> I had the same issue all day yesterday after updating, downgraded today and all is fine again.

downgraded to which version @Weiss68 ? Tried downgrading my docker container to 2022.10.4 then to 2022.10.3 and it still doesn't work

**Comment by amamoh** [comment]
Downgrading to 10.4 works, HAOS in VirtualBox

Home Assistant 2022.10.4
Supervisor 2022.10.2
Operating System 9.3
Interfejs użytkownika: 20221010.0 - latest

**Comment by spitfire** [comment]
> Downgrading to 10.4 works, HAOS in VirtualBox
> 
> Home Assistant 2022.10.4 Supervisor 2022.10.2 Operating System 9.3 Interfejs użytkownika: 20221010.0 - latest

Just noticed I didn't actually run, just pulled 10.4. works now, thanks for the reply!

**Comment by kevinverelst** [comment]
Tried debugging this issue and so far I learned that HA has a helper rest class to do API calls. This class uses httpx underlying but it seems HA migrated to httpx in 2020 and can't seem to pinpoint what the difference is between releases that is causing this issue. It does not help that my python is terrible.

**Comment by domerich** [comment]
for n00bs like me it took a while to find the correct ssh command:

`ha core update --version=2022.10.4`

**Comment by amamoh** [comment]
oh, that's cool, I've just restored backup

**Comment by Grimroper** [comment]
Ive just updated to Home Assistant Core 2022.11.02 and the issue still persists

**Comment by sebastian-bugajny** [comment]
> Ive just updated to Home Assistant Core 2022.11.2 and the issue still persists

Thanks for an update I was about to do the same.

**Comment by seanwelsh** [comment]
There has been a change to the RestData helper in the home assistant libraries to use 'content' instead of 'data' for the POST payload.  No idea if this was done in error or not.

A temp fix to get foxess working in meantime is to change line 177 of /config/custom_components/foxess/sensor.py to:
```py
payloadAuth = f'user={username}&password={hashedPassword}'
```
That looks like it should get it working as per logs  - no sun right now so cant see energy dashboard updates.  

I'll defer to the maintainer as to how this should be fixed permanently

**Comment by seanwelsh** [comment]
There has been a change to the RestData helper in the home assistant libraries to use 'content' instead of 'data' for the POST payload.  No idea if this was done in error or not.

A temp fix to get foxess working in meantime is to change line 177 of /config/custom_components/foxess/sensor.py to:
```py
payloadAuth = f'user={username}&password={hashedPassword}'
```
That looks like it should get it working as per logs  - no sun right now so cant see energy dashboard updates.  

I'll defer to the maintainer as to how this should be fixed permanently

**Comment by fragamot** [comment]
There has been a change to the RestData helper in the home assistant libraries to use 'content' instead of 'data' for the POST payload.  No idea if this was done in error or not.

A temp fix to get foxess working in meantime is to change line 177 of /config/custom_components/foxess/sensor.py to:
```py
payloadAuth = f'user={username}&password={hashedPassword}'
```
That looks like it should get it working as per logs  - no sun right now so cant see energy dashboard updates.  

I'll defer to the maintainer as to how this should be fixed permanently

**Comment by alexmercerscott** [comment]
I've changed the code you suggested, and will wait for sunrise. But, my installation is battery-only, the solar panel inverter is GroWatt and dealt with separately. Point being, with the change suggested (thank you for at least offering hope!) all the previous sensors still show as 'unavailable'. I shouldn't need to wait for sunrise, as it's interrogating the battery status. If that makes sense.

**Comment by fragamot** [comment]
> I've changed the code you suggested, and will wait for sunrise. But, my installation is battery-only, the solar panel inverter is GroWatt and dealt with separately. Point being, with the change suggested (thank you for at least offering hope!) all the previous sensors still show as 'unavailable'. I shouldn't need to wait for sunrise, as it's interrogating the battery status. If that makes sense.

As you are battery only the sun shouldn't matter. Switch on debug logging as described in the README on the main page and check your logs. The error should not occur and you should see the data coming in.

**Comment by alexmercerscott** [comment]
Okay, your suggestion DOES work... I added the debug instructions for the log which was showing an "cannot log in, incorrect name and password" type error (I didn't note it down exactly). So I re-copied and pasted your code just in case I formatted it incorrectly, and did another reboot. 

And my sensors have all come back!

**Comment by fragamot** [comment]
Thats a timeout: "Timeout while fetching data". Likely problem with the foxess server. I got same about same time. Looks ok now for me

**Comment by alexmercerscott** [comment]
Okay, I'll keep an eye on mine and see what the story is in 24hrs time. You may have just cracked it...

**Comment by Grimroper** [comment]
In case anyone is interested I made the changes above suggested by @fragamot whilst I was still on 2022.10.5 and can confirm it worked on that version too.  Im now on 2022.11.2 where they are working as others have said above.

**Comment by tagware** [comment]
The temporary amendment worked fine for me. Thanks for that. :o)

However, be careful to line up the text carefully in the editor as HA is strict on indent rules. Which, might be why some are not working.  See below 

![image](https://user-images.githubusercontent.com/28730091/201079420-9069bcfa-04c4-4fb5-8a0a-3109f3631661.png)

**Comment by sebastian-bugajny** [comment]
This fix works fine on version 2022.11.2

**Comment by spitfire** [comment]
> There has been a change to the RestData helper in the home assistant libraries to use 'content' instead of 'data' for the POST payload.  No idea if this was done in error or not.
> 
> 
> 
> A temp fix to get foxess working in meantime is to change line 177 of /config/custom_components/foxess/sensor.py to:
> 
> ```py
> 
> payloadAuth = f'user={username}&password={hashedPassword}'
> 
> ```
> 
> That looks like it should get it working as per logs  - no sun right now so cant see energy dashboard updates.  
> 
> 
> 
> I'll defer to the maintainer as to how this should be fixed permanently

Can you create a pull request to the dev? I'd do it myself but I don't want to take (steal?) a credit for it.

**Comment by gellscom** [comment]
Hi the above fix worked fine for me on Core 2022.11.2 but it seem to have fallen over on 2022.11.3. I tried undoing the above fix and reverting to the original but that didnt work. I'm out of my depth now hoping you guys can figure a fix.

**Comment by alexmercerscott** [comment]
Having fixed mine previously by adjusting the code, mine has also stopped working again on the 2022.11.3 update. This is highly frustrating when there are automations based on solar activity...!

I've also tried going back to the original sensor.py file, but the original error re-appears. So 2022.11.3 has not fixed the original problem, and has caused a new issue.

I now get a Timeout, followed by No Data, followed by "bool object has no attribute", followed by the original initialisation error:

`Logger: homeassistant.components.rest.data
Source: components/rest/data.py:77 
Integration: RESTful (documentation, issues) 
First occurred: 19:01:43 (1 occurrences) 
Last logged: 19:01:43

Timeout while fetching data: https://www.foxesscloud.com/c/v0/user/login

-----

This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:164 
Integration: foxess (documentation, issues) 
First occurred: 19:01:43 (1 occurrences) 
Last logged: 19:01:43

Unable to login to FoxESS Cloud - No data recived

-----

This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: components/rest/data.py:63 
Integration: foxess (documentation, issues) 
First occurred: 19:01:43 (1 occurrences) 
Last logged: 19:01:43

Unexpected error fetching FoxESS data: 'bool' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 139, in async_update_data
    await getAddresbook(hass, headersData, allData, deviceID, username, hashedPassword,0)
  File "/config/custom_components/foxess/sensor.py", line 220, in getAddresbook
    await restAddressBook.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1514, in request
    request = self.build_request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 345, in build_request
    headers = self._merge_headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 412, in _merge_headers
    merged_headers.update(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 198, in update
    headers = Headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 69, in __init__
    self._list = [
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 73, in <listcomp>
    normalize_header_value(v, encoding),
  File "/usr/local/lib/python3.10/site-packages/httpx/_utils.py", line 54, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'bool' object has no attribute 'encode'

-----

This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:167 
Integration: foxess (documentation, issues) 
First occurred: 19:01:43 (1 occurrences) 
Last logged: 19:01:43

FoxESS Cloud initializaction failed, fix error and restar ha

`

**Comment by pattos123** [comment]
This patch for line#177 works for me on latest 2022.11.3

**Comment by Grimroper** [comment]
> > Hi the above fix worked fine for me on Core 2022.11.2 but it seem to have fallen over on 2022.11.3. I tried undoing the above fix and reverting to the original but that didnt work. I'm out of my depth now hoping you guys can figure a fix.
> 
> Id updated to 2022.11.3 as well and it was working fine. It was showing the entities as unavailable for a short while Ive just noticed but now they are back up and popuating. Maybe it was an issue on the FoxESS server side?

Im not sure if its a coincidence or not but since upgrading to 2022.11.3 Ive found the FoxESS Integration does seem to become unavailable for short periods of time quite often.  It could be something on the Fox side or something to do with HA but downgrading back to 11.2 it doesnt appear to be as flaky.

**Comment by Bartolini177** [comment]
For all who are tired of foxess clouds.  here is a great solution:
https://github.com/assembly12/Foxess-T-series-ESPHome-Home-Assistant/wiki/Hardware-setup

**Comment by macxq** [comment]
fixed in v0.16  thanks to @guba91
